apiVersion: v1
kind: ConfigMap
metadata:
  name: otp-pugetsound-config
data:
  graph-url: https://data.example.com/0.9.0/maps-earth-planet-v1.43/PugetSound.graph.obj.zst
  router-config-json: |
    {
      "configVersion": "2023-05-24",
      "updaters": [
        {
          "feedId": "headway-1080",
          "type": "stop-time-updater",
          "frequencySec": 60,
          "url": "https://s3.amazonaws.com/kcm-alerts-realtime-prod/tripupdates.pb"
        },
        {
          "feedId": "headway-1080",
          "type": "real-time-alerts",
          "frequencySec": 300,
          "url": "https://s3.amazonaws.com/kcm-alerts-realtime-prod/alerts.pb"
        }
      ]
    }

