apiVersion: v1
kind: ConfigMap
metadata:
  name: otp-losangeles-config
data:
  graph-url: https://data.example.com/0.10.0/maps-earth-planet-v1.250623/LosAngeles.graph.obj.zst
  otp-config-json: |
    {
        "otpFeatures" : {
            "LegacyRestApi": true
        }
    }
  router-config-json: ""

