apiVersion: v1
kind: ConfigMap
metadata:
  name: deployment-config
data:
  area: Seattle
  public-url: https://seattle.maps.earth
  bbox: "-122.462 47.394 -122.005 47.831"
  enable-transit-routing: "1"
  www-about-url: "https://about.maps.earth"
  www-about-link-text: "About maps.earth"
  www-contact-url: "mailto:info@maps.earth?subject=Hello,%20Earth"
  www-contact-link-text: "Contact Us"
  terrain-source-url: https://data.example.com/dev/terrain.mbtiles
  landcover-source-url: https://data.example.com/dev/landcover.mbtiles
  areamap-source-url: https://data.example.com/dev/seattle-latest/Seattle.mbtiles
  valhalla-artifact-url: https://data.example.com/dev/seattle-latest/Seattle.valhalla.tar.zst
  placeholder-artifact-url: https://data.example.com/dev/seattle-latest/Seattle.placeholder.tar.zst
  elasticsearch-artifact-url: https://data.example.com/dev/seattle-latest/Seattle.elasticsearch.tar.zst
  pelias-config-json: |
    {
      "logger": {
        "level": "info",
        "timestamp": false
      },
      "esclient": {
        "apiVersion": "7.5",
        "hosts": [
          {
            "host": "pelias-elasticsearch"
          }
        ]
      },
      "elasticsearch": {
        "settings": {
          "index": {
            "refresh_interval": "10s",
            "number_of_replicas": "0",
            "number_of_shards": "5"
          }
        }
      },
      "api": {
        "services": {
          "placeholder": {
            "url": "http://pelias-placeholder:4100"
          },
          "libpostal": {
            "url": "http://pelias-libpostal:4400"
          },
          "pip": {
            "url": "http://pelias-pip:4400"
          }
        }
      },
      "imports": {
        "adminLookup": {
          "enabled": true
        },
        "openstreetmap": {
          "leveldbpath": "/tmp",
          "datapath": "/data/openstreetmap",
          "import": [
            {
              "filename": "data.osm.pbf"
            }
          ]
        },
        "whosonfirst": {
          "datapath": "/data/whosonfirst",
          "importPostalcodes": true,
          "countryCode": [
            "US"
          ]
        },
        "polyline": {
          "datapath": "/data/polylines",
          "files": [
            "extract.0sv"
          ]
        },
        "openaddresses": {
          "datapath": "/data/openaddresses",
          "files": [
            "us/wa/king.csv"
          ]
        }
      }
    }
